base_url = "https://samtee.uk"
title = "Sam Larcombe Tee"
description = "MSci Physics, Cambridge. Computational physics, Python, tutoring."

[extra]
name = "Sam Larcombe Tee"
email = "sl2110@cam.ac.uk"
git_url = "https://git.akhlus.uk"
author = "Sam Larcombe Tee"
variant = "Minimal Masthead"
